name: build-sample

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu-tcc:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    env:
      VFLAGS: -cc tcc
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - uses: actions/checkout@v2
        with:
          path: vargus

      - name: Build local V
        run: make -j4

      - name: Install vargus
        run: ./v install TheBoringDude.vargus

      - name: Build and run sample file
        run: ./v run vargus/example/sample.v
