name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ubuntu-tcc:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      VFLAGS: -cc tcc -no-retry-compilation
    steps:
    -name: Checkout V
    with:
      repository: vlang/v
    - name: Build local V
      run: make -j4
    - uses: actions/checkout@v2
    - name: Run all tests
      run: ./v -stats test .
